- name: directory
  desc: an example variable
  choices:
    - value: /etc
      desc: etc acpi directory
    - value: /etc/default
      desc: etc default directory

- name: pager
  desc: the pager tool to use
  choices: 
    - value: less
      desc: use less
    - value: cat
      desc: use cat


- name: file
  desc: file selection
  from_command: "sleep 10 && ls -1 {{ directory }}"

- name: value
  desc: file selection
  from_input: "select an input"
